variable "vpc_cidr" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "az1" {}
variable "env" {}
variable "allowed_ip" {}
variable "ami_id" {}
variable "key_name" {}
variable "private_subnet_cidr_2" {}
variable "az2" {}
